name: Deploy Locus Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          # Ensure data files are copied
          mkdir -p dist/data
          cp -r src/data/* dist/data/
          echo "Verifying data files:"
          ls -la dist/data/

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add Known Hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          DEPLOY_HOST: ${{ secrets.VPS_HOST }}
          DEPLOY_USER: ${{ secrets.VPS_USER }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          FRONTEND_DEV_URL: ${{ secrets.FRONTEND_DEV_URL }}
          PORT: ${{ secrets.PORT }}
        run: |
          # Create .env file content
          ENV_CONTENT="JWT_SECRET=\"${JWT_SECRET}\"\n\
          FRONTEND_URL=\"${FRONTEND_URL}\"\n\
          FRONTEND_DEV_URL=\"${FRONTEND_DEV_URL}\"\n\
          PORT=${PORT}\n\
          NODE_ENV=production"

          # Create deployment package
          tar -czf deploy_package.tar.gz dist/ package*.json ecosystem.config.js

          # Copy files to server
          echo "Copying deployment package to server..."
          scp -i ~/.ssh/deploy_key deploy_package.tar.gz $DEPLOY_USER@$DEPLOY_HOST:/var/www/locus-backend/

          # Deploy and update environment
          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST "
            set -e
            export PATH=/home/deploy/.nvm/versions/node/v22.11.0/bin:\$PATH
            cd /var/www/locus-backend

            echo 'Stopping PM2 processes...'
            pm2 delete all || true
            pm2 flush

            echo 'Creating required directories...'
            mkdir -p logs

            echo 'Cleaning up old files...'
            rm -rf dist releases current
            rm -f package*.json ecosystem.config.js

            echo 'Extracting new files...'
            tar xzf deploy_package.tar.gz
            rm -f deploy_package.tar.gz

            echo 'Setting up environment...'
            echo -e \"$ENV_CONTENT\" > .env

            echo 'Setting correct permissions...'
            chmod 755 /var/www/locus-backend
            chmod -R 755 dist
            chmod 644 .env
            chmod 644 package*.json
            chmod 644 ecosystem.config.js
            chmod -R 755 logs

            echo 'Installing production dependencies...'
            npm ci --omit=dev

            echo 'Verifying deployment...'
            echo 'Directory structure:'
            ls -la
            echo 'Data files:'
            ls -la dist/data/
            echo 'Content of work.json:'
            cat dist/data/work.json | head -n 5
            echo 'Node version:'
            node --version
            echo 'PM2 version:'
            pm2 --version
            
            echo 'Starting application...'
            pm2 start ecosystem.config.js --env production --wait-ready

            echo 'Saving PM2 configuration...'
            pm2 save

            echo 'PM2 status:'
            pm2 list
            
            echo 'Checking application logs:'
            tail -n 50 logs/error.log || true
            tail -n 50 logs/out.log || true

            echo 'Deployment complete!'
          " 
