name: Deploy Locus Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          # Verify data files were copied
          ls -la dist/data/
          cat dist/data/work.json | head -n 1

      - name: Create deployment package
        run: |
          tar -czf deploy_package.tar.gz dist/ package*.json

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add Known Hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          # Create .env file content
          ENV_CONTENT="JWT_SECRET=\"${{ secrets.JWT_SECRET }}\"\n\
          FRONTEND_URL=\"${{ secrets.FRONTEND_URL }}\"\n\
          FRONTEND_DEV_URL=\"${{ secrets.FRONTEND_DEV_URL }}\"\n\
          PORT=${{ secrets.PORT }}\n\
          NODE_ENV=production"

          # Copy deployment package to VPS
          scp -i ~/.ssh/deploy_key deploy_package.tar.gz ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/locus-backend/

          # Deploy and update environment
          ssh -i ~/.ssh/deploy_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            export PATH=/home/deploy/.nvm/versions/node/v22.11.0/bin:\$PATH &&
            cd /var/www/locus-backend &&
            
            # Backup current .env if it exists
            [ -f .env ] && cp .env .env.backup || true
            
            # Create new release directory with timestamp
            RELEASE_DIR=\"releases/\$(date +%Y%m%d%H%M%S)\" &&
            mkdir -p \"\$RELEASE_DIR/dist\" &&
            
            # Extract files and move them to the release directory
            tar xzf deploy_package.tar.gz &&
            cp -r dist/* \"\$RELEASE_DIR/dist/\" &&
            cp package*.json \"\$RELEASE_DIR/\" &&
            rm -f deploy_package.tar.gz &&
            rm -rf dist &&
            
            # Update current symlink
            ln -nfs \"\$RELEASE_DIR\" current &&
            
            # Create .env in the new release
            echo -e \"$ENV_CONTENT\" > \"\$RELEASE_DIR/.env\" &&
            
            # Install production dependencies in the new release
            cd \"\$RELEASE_DIR\" &&
            npm ci --omit=dev &&
            
            # Verify data files are present
            echo 'Checking data files in new release...' &&
            ls -la dist/data/ &&
            
            # Restart PM2 to use the new release
            cd /var/www/locus-backend &&
            pm2 reload all --update-env
          " 
